# Generated by Django 5.1.1 on 2024-10-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_game_offer_price_alter_game_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='region',
        ),
    ]
