# Generated by Django 5.1.1 on 2024-10-08 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
