# Generated by Django 5.1.1 on 2024-10-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='account_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
