# Generated by Django 5.1.1 on 2024-10-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_game_account_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=100, null=True),
        ),
    ]
