# Generated by Django 5.1.1 on 2024-10-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_tracking_code_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commission',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
