# Generated by Django 5.1.1 on 2024-11-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
