# Generated by Django 5.1.1 on 2024-11-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_product_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
