# Generated by Django 5.1.1 on 2024-11-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_state_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
